version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQL_DB?
            useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true",
            "spring.datasource.username" : "$MYSQL_USER",
            "spring.datasource.password" : "$MYSQL_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "$HIBERNATE_DIALECT",
            "spring.jpa.hibernate.ddl-auto" : "$HIBERNATE_DDL_AUTO"
          }'